// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0S-AazvwSuVNo11EevfUe_nU71KEPpkU',
    appId: '1:340692822620:web:63c5b8b942f25d5ab31499',
    messagingSenderId: '340692822620',
    projectId: 'foodhub-2ee3c',
    authDomain: 'foodhub-2ee3c.firebaseapp.com',
    storageBucket: 'foodhub-2ee3c.appspot.com',
    measurementId: 'G-CGHXPJEGQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4r-U61Rvot0fRMBSBajV8ckue55WL-J4',
    appId: '1:340692822620:android:ae34b568a83d6fdcb31499',
    messagingSenderId: '340692822620',
    projectId: 'foodhub-2ee3c',
    storageBucket: 'foodhub-2ee3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmydm6ycwfzEqDjSo81a4HdepR1jYSjC8',
    appId: '1:340692822620:ios:39eef53fd77873a5b31499',
    messagingSenderId: '340692822620',
    projectId: 'foodhub-2ee3c',
    storageBucket: 'foodhub-2ee3c.appspot.com',
    iosBundleId: 'com.example.chefapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmydm6ycwfzEqDjSo81a4HdepR1jYSjC8',
    appId: '1:340692822620:ios:39eef53fd77873a5b31499',
    messagingSenderId: '340692822620',
    projectId: 'foodhub-2ee3c',
    storageBucket: 'foodhub-2ee3c.appspot.com',
    iosBundleId: 'com.example.chefapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0S-AazvwSuVNo11EevfUe_nU71KEPpkU',
    appId: '1:340692822620:web:d372bf6f2f441489b31499',
    messagingSenderId: '340692822620',
    projectId: 'foodhub-2ee3c',
    authDomain: 'foodhub-2ee3c.firebaseapp.com',
    storageBucket: 'foodhub-2ee3c.appspot.com',
    measurementId: 'G-TPHZCSZHB6',
  );
}
